"""create hypotheses and evidence relationships

Revision ID: 8c08b9d97e05
Revises: 1d26d8b9e32a
Create Date: 2026-09-18 12:01:13.599872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c08b9d97e05'
down_revision: Union[str, Sequence[str], None] = '1d26d8b9e32a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hypotheses',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('incident_id', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypotheses_incident_id'), 'hypotheses', ['incident_id'], unique=False)
    op.create_table('hypothesis_evidence',
    sa.Column('hypothesis_id', sa.String(length=50), nullable=False),
    sa.Column('evidence_id', sa.String(length=50), nullable=False),
    sa.Column('relationship_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hypothesis_id', 'evidence_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hypothesis_evidence')
    op.drop_index(op.f('ix_hypotheses_incident_id'), table_name='hypotheses')
    op.drop_table('hypotheses')
    # ### end Alembic commands ###
